USE [OrderManagement]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [DBO].[PLACE_OR_MODFY_ORDER]
	@ORDER_ID BIGINT--999 will be passed as the id if it is a new ORDER else the actualy orderid will be passed
    ,@PRODUCTS_TVP [PRODUCTS_TVP] READONLY
	,@USER BIGINT
	,@H_NO NVARCHAR(20)
	,@STREET NVARCHAR(MAX)
	,@CITY  NVARCHAR(MAX)
	,@STATE NVARCHAR(MAX)
	,@PINCODE BIGINT
	,@RECIEVER_NAME NVARCHAR(MAX)
	,@RECIEVER_PHONE BIGINT
AS 
BEGIN

DECLARE @ADRESS_UID BIGINT
	IF NOT EXISTS(SELECT 1 FROM [DBO].[ADDRESS] WHERE A_PINCOCDE=@PINCODE
												AND A_STATE=@STATE
												AND A_CITY=@CITY
												AND A_U_UID=@USER
												AND A_STREET=@STREET
												AND A_RECIEPIENT_NAME=@RECIEVER_NAME
												AND A_RECIEPIENT_MOBILE=@RECIEVER_PHONE
												AND A_HOUSE_NUM= @H_NO)
	BEGIN
		INSERT INTO [DBO].[ADDRESS](
		A_RECIEPIENT_NAME
		,A_RECIEPIENT_MOBILE
		,A_HOUSE_NUM
		,A_STREET
		,A_CITY
		,A_STATE
		,A_PINCOCDE
		,A_U_UID
		)
		SELECT @RECIEVER_NAME
		,@RECIEVER_PHONE
		,@H_NO
		,@STREET
		,@CITY
		,@STATE
		,@PINCODE
		,@USER

		SET @ADRESS_UID= SCOPE_IDENTITY()
	END
	ELSE
	BEGIN
		SET @ADRESS_UID= (SELECT A_UID FROM [DBO].[ADDRESS] WHERE A_PINCOCDE=@PINCODE
												AND A_STATE=@STATE
												AND A_CITY=@CITY
												AND A_U_UID=@USER
												AND A_STREET=@STREET
												AND A_RECIEPIENT_NAME=@RECIEVER_NAME
												AND A_RECIEPIENT_MOBILE=@RECIEVER_PHONE
												AND A_HOUSE_NUM= @H_NO)
	END


	INSERT INTO [DBO].[ORDERS](
	O_U_UID
	,O_A_UID
	,O_OS_UID
	,O_ORDERDATE
	)
	SELECT @USER
	,@ADRESS_UID
	,OS_UID
	,GETDATE()
	FROM [ORDER_STATUS]
	WHERE OS_NAME='Placed'
	AND @ORDER_ID=-999

	IF(@ORDER_ID=-999)
	BEGIN 
		SET @ORDER_ID=SCOPE_IDENTITY()
	END

	INSERT  INTO [ORDER_REL_PRODUCT](
	ORU_O_UID
	,ORU_P_UID
	,ORU_QUANTITY
	)
	SELECT @ORDER_ID
	,PRODUCT_ID
	,QUANTITY
	FROM @PRODUCTS_TVP
	LEFT JOIN [ORDER_REL_PRODUCT]
	ON ORU_O_UID=@ORDER_ID
	AND  ORU_P_UID=PRODUCT_ID
	WHERE ORU_UID IS NULL

	UPDATE ORU
	SET ORU_QUANTITY=QUANTITY
	FROM @PRODUCTS_TVP
	JOIN [ORDER_REL_PRODUCT] ORU
	ON ORU_O_UID=@ORDER_ID
	AND  ORU_P_UID=PRODUCT_ID
END