USE [OrderManagement]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
Purpose- To fetch all orders on the basis of role
exec DBO.GET_ORDERS 1
*/
CREATE PROCEDURE DBO.GET_ORDERS
	@USER BIGINT
AS 
BEGIN

DECLARE @ROLE_NAME NVARCHAR(MAX)=(SELECT R_NAME FROM [USERS]
									JOIN [ROLE]
									ON U_R_UID=R_UID
									AND U_UID=@USER)
	SELECT O_UID AS ORDER_UID
	,OS_NAME AS ORDER_STATUS
	,U_UID AS BUYER_UID
	,U_FIRSTNAME+' '+U_LASTNAME AS BUYER_NAME
	,A_RECIEPIENT_NAME AS [NAME]
	,A_HOUSE_NUM  AS H_NO
	,A_CITY AS CITY
	,A_STREET AS STREET
	,A_STATE AS [STATE]
	INTO #TEMP_ORDERS
	FROM [ORDERS] (NOLOCK)
	JOIN [USERS] BUYER (NOLOCK)
	ON O_U_UID=U_UID
	AND U_UID= (CASE WHEN @ROLE_NAME='Buyer'
				THEN @USER
				ELSE U_UID 
				END )
	JOIN [ORDER_STATUS] (NOLOCK)
	ON OS_UID=O_OS_UID
	JOIN [ADDRESS] (NOLOCK)
	ON A_UID=O_A_UID

	SELECT * FROM #TEMP_ORDERS

	SELECT ORU_O_UID AS ORDER_UID
		,ORU_QUANTITY AS QUANTITY
		,P_UID AS PRODUCT_ID
		,P_NAME AS PRODUCT_NAME
	FROM [ORDER_REL_PRODUCT]
	JOIN [PRODUCTS]
	ON P_UID=ORU_QUANTITY
	JOIN #TEMP_ORDERS
	ON ORU_O_UID=ORDER_UID



END