USE [OrderManagement]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
exec DBO.delete_ORDER 1
*/
CREATE PROCEDURE DBO.DELETE_ORDER
	@ORDER_ID BIGINT
AS 
BEGIN
	DELETE FROM [ORDER_REL_PRODUCT]
	WHERE ORU_O_UID=@ORDER_ID

	DELETE FROM [ORDERS]
	WHERE O_UID=@ORDER_ID
END